### ISSUE TITLE
devkit install is breaking

### ISSUE THREAD

**Issue by jishnu7** [gameclosure/devkit-core#38]
reason:

jsio is specified as both node package and git submodule. 
When you run `npm install` node module installs first. Then when it reaches `git submodule init` stage, since there already exists a folder, script is breaking.

**Comment by misterunix** [comment]
editing out jsio didnt did not solve it for me.

[root@develop devkit-core]# npm uninstall -g devkit
- after@0.8.1 node_modules/devkit/node_modules/after
- ansi-regex@2.0.0 node_modules/devkit/node_modules/ansi-regex
- ansi-styles@2.1.0 node_modules/devkit/node_modules/ansi-styles
- array-flatten@1.1.1 node_modules/devkit/node_modules/array-flatten
- arraybuffer.slice@0.0.6 node_modules/devkit/node_modules/arraybuffer.slice
- backo2@1.0.2 node_modules/devkit/node_modules/backo2
- balanced-match@0.2.0 node_modules/devkit/node_modules/balanced-match
- base64-arraybuffer@0.1.2 node_modules/devkit/node_modules/base64-arraybuffer
- base64id@0.1.0 node_modules/devkit/node_modules/base64id
- benchmark@1.0.0 node_modules/devkit/node_modules/benchmark
- bindings@1.2.1 node_modules/devkit/node_modules/bindings
- blob@0.0.4 node_modules/devkit/node_modules/blob
- bluebird@2.10.2 node_modules/devkit/node_modules/bluebird
- bytes@2.1.0 node_modules/devkit/node_modules/bytes
- callsite@1.0.0 node_modules/devkit/node_modules/callsite
- better-assert@1.0.2 node_modules/devkit/node_modules/better-assert
- component-bind@1.0.0 node_modules/devkit/node_modules/component-bind
- component-emitter@1.1.2 node_modules/devkit/node_modules/component-emitter
- component-inherit@0.0.3 node_modules/devkit/node_modules/component-inherit
- concat-map@0.0.1 node_modules/devkit/node_modules/concat-map
- brace-expansion@1.1.1 node_modules/devkit/node_modules/brace-expansion
- content-disposition@0.5.0 node_modules/devkit/node_modules/content-disposition
- content-type@1.0.1 node_modules/devkit/node_modules/content-type
- cookie@0.1.3 node_modules/devkit/node_modules/cookie
- cookie-signature@1.0.6 node_modules/devkit/node_modules/cookie-signature
- depd@1.1.0 node_modules/devkit/node_modules/depd
- destroy@1.0.3 node_modules/devkit/node_modules/destroy
- ee-first@1.1.1 node_modules/devkit/node_modules/ee-first
- ms@0.6.2 node_modules/devkit/node_modules/engine.io-client/node_modules/ms
- debug@1.0.4 node_modules/devkit/node_modules/engine.io-client/node_modules/debug
- parseuri@0.0.4 node_modules/devkit/node_modules/engine.io-client/node_modules/parseuri
- ms@0.6.2 node_modules/devkit/node_modules/engine.io/node_modules/ms
- debug@1.0.3 node_modules/devkit/node_modules/engine.io/node_modules/debug
- escape-html@1.0.2 node_modules/devkit/node_modules/escape-html
- escape-string-regexp@1.0.3 node_modules/devkit/node_modules/escape-string-regexp
- esprima@2.2.0 node_modules/devkit/node_modules/esprima
- etag@1.7.0 node_modules/devkit/node_modules/etag
- depd@1.0.1 node_modules/devkit/node_modules/express/node_modules/depd
- negotiator@0.5.3 node_modules/devkit/node_modules/express/node_modules/negotiator
- qs@4.0.0 node_modules/devkit/node_modules/express/node_modules/qs
- vary@1.0.1 node_modules/devkit/node_modules/express/node_modules/vary
- ff@0.2.1 node_modules/devkit/node_modules/ff
- filesize@3.1.3 node_modules/devkit/node_modules/filesize
- forwarded@0.1.0 node_modules/devkit/node_modules/forwarded
- fresh@0.3.0 node_modules/devkit/node_modules/fresh
- global@2.0.1 node_modules/devkit/node_modules/global
- graceful-fs@4.1.2 node_modules/devkit/node_modules/graceful-fs
- has-ansi@2.0.0 node_modules/devkit/node_modules/has-ansi
- has-cors@1.0.3 node_modules/devkit/node_modules/has-cors
- iconv-lite@0.4.12 node_modules/devkit/node_modules/iconv-lite
- indexof@0.0.1 node_modules/devkit/node_modules/indexof
- inherits@2.0.1 node_modules/devkit/node_modules/inherits
- ipaddr.js@1.0.1 node_modules/devkit/node_modules/ipaddr.js
- isarray@0.0.1 node_modules/devkit/node_modules/isarray
- has-binary-data@0.1.3 node_modules/devkit/node_modules/has-binary-data
- has-binary@0.1.6 node_modules/devkit/node_modules/has-binary
- jsio@2.2.4 node_modules/devkit/node_modules/jsio
- json3@3.2.6 node_modules/devkit/node_modules/json3
- jsonfile@2.2.2 node_modules/devkit/node_modules/jsonfile
- lockfile@1.0.1 node_modules/devkit/node_modules/lockfile
- lodash@3.10.1 node_modules/devkit/node_modules/lodash
- media-typer@0.3.0 node_modules/devkit/node_modules/media-typer
- merge-descriptors@1.0.0 node_modules/devkit/node_modules/merge-descriptors
- methods@1.1.1 node_modules/devkit/node_modules/methods
- mime@1.3.4 node_modules/devkit/node_modules/mime
- mime-db@1.19.0 node_modules/devkit/node_modules/mime-db
- compressible@2.0.6 node_modules/devkit/node_modules/compressible
- mime-types@2.1.7 node_modules/devkit/node_modules/mime-types
- accepts@1.2.13 node_modules/devkit/node_modules/express/node_modules/accepts
- minimatch@3.0.0 node_modules/devkit/node_modules/minimatch
- minimist@0.0.10 node_modules/devkit/node_modules/minimist
- ms@0.7.1 node_modules/devkit/node_modules/ms
- debug@2.2.0 node_modules/devkit/node_modules/debug
- nan@2.0.9 node_modules/devkit/node_modules/nan
- bufferutil@1.2.1 node_modules/devkit/node_modules/bufferutil
- negotiator@0.6.0 node_modules/devkit/node_modules/negotiator
- accepts@1.3.0 node_modules/devkit/node_modules/accepts
- object-component@0.0.3 node_modules/devkit/node_modules/object-component
- object-keys@1.0.1 node_modules/devkit/node_modules/object-keys
- on-finished@2.3.0 node_modules/devkit/node_modules/on-finished
- on-headers@1.0.1 node_modules/devkit/node_modules/on-headers
- open@0.0.5 node_modules/devkit/node_modules/open
- options@0.0.6 node_modules/devkit/node_modules/options
- parsejson@0.0.1 node_modules/devkit/node_modules/parsejson
- parseqs@0.0.2 node_modules/devkit/node_modules/parseqs
- parseuri@0.0.2 node_modules/devkit/node_modules/parseuri
- parseurl@1.3.0 node_modules/devkit/node_modules/parseurl
- path-extra@1.0.3 node_modules/devkit/node_modules/path-extra
- path-is-absolute@1.0.0 node_modules/devkit/node_modules/path-is-absolute
- path-to-regexp@0.1.7 node_modules/devkit/node_modules/path-to-regexp
- printf@0.2.3 node_modules/devkit/node_modules/printf
- proxy-addr@1.0.8 node_modules/devkit/node_modules/proxy-addr
- qs@5.1.0 node_modules/devkit/node_modules/qs
- range-parser@1.0.2 node_modules/devkit/node_modules/range-parser
- semver@4.3.6 node_modules/devkit/node_modules/semver
- depd@1.0.1 node_modules/devkit/node_modules/send/node_modules/depd
- ms@0.6.2 node_modules/devkit/node_modules/socket.io-adapter/node_modules/ms
- debug@1.0.2 node_modules/devkit/node_modules/socket.io-adapter/node_modules/debug
- debug@0.7.4 node_modules/devkit/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug
- socket.io-parser@2.2.2 node_modules/devkit/node_modules/socket.io-adapter/node_modules/socket.io-parser
- socket.io-adapter@0.3.1 node_modules/devkit/node_modules/socket.io-adapter
- debug@0.7.4 node_modules/devkit/node_modules/socket.io-client/node_modules/debug
- debug@0.7.4 node_modules/devkit/node_modules/socket.io-parser/node_modules/debug
- socket.io-parser@2.2.4 node_modules/devkit/node_modules/socket.io-parser
- ms@0.6.2 node_modules/devkit/node_modules/socket.io/node_modules/ms
- debug@2.1.0 node_modules/devkit/node_modules/socket.io/node_modules/debug
- sprintf-js@1.0.3 node_modules/devkit/node_modules/sprintf-js
- argparse@1.0.2 node_modules/devkit/node_modules/argparse
- js-yaml@3.4.2 node_modules/devkit/node_modules/js-yaml
- statuses@1.2.1 node_modules/devkit/node_modules/statuses
- http-errors@1.3.1 node_modules/devkit/node_modules/http-errors
- send@0.13.0 node_modules/devkit/node_modules/send
- serve-static@1.10.0 node_modules/devkit/node_modules/serve-static
- strip-ansi@3.0.0 node_modules/devkit/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/devkit/node_modules/supports-color
- chalk@1.1.1 node_modules/devkit/node_modules/chalk
- to-array@0.1.3 node_modules/devkit/node_modules/to-array
- type-is@1.6.9 node_modules/devkit/node_modules/type-is
- ultron@1.0.2 node_modules/devkit/node_modules/ultron
- unpipe@1.0.0 node_modules/devkit/node_modules/unpipe
- raw-body@2.1.4 node_modules/devkit/node_modules/raw-body
- body-parser@1.14.1 node_modules/devkit/node_modules/body-parser
- finalhandler@0.4.0 node_modules/devkit/node_modules/finalhandler
- utf-8-validate@1.2.1 node_modules/devkit/node_modules/utf-8-validate
- utf8@2.1.0 node_modules/devkit/node_modules/utf8
- engine.io-parser@1.2.2 node_modules/devkit/node_modules/engine.io-parser
- utils-merge@1.0.0 node_modules/devkit/node_modules/utils-merge
- express@4.13.3 node_modules/devkit/node_modules/express
- vary@1.1.0 node_modules/devkit/node_modules/vary
- compression@1.6.0 node_modules/devkit/node_modules/compression
- wordwrap@0.0.3 node_modules/devkit/node_modules/wordwrap
- optimist@0.6.1 node_modules/devkit/node_modules/optimist
- wrappy@1.0.1 node_modules/devkit/node_modules/wrappy
- once@1.3.2 node_modules/devkit/node_modules/once
- inflight@1.0.4 node_modules/devkit/node_modules/inflight
- glob@5.0.15 node_modules/devkit/node_modules/glob
- rimraf@2.4.3 node_modules/devkit/node_modules/rimraf
- fs-extra@0.24.0 node_modules/devkit/node_modules/fs-extra
- ws@0.8.0 node_modules/devkit/node_modules/ws
- engine.io@1.5.4 node_modules/devkit/node_modules/engine.io
- xmlhttprequest@1.5.0 node_modules/devkit/node_modules/xmlhttprequest
- engine.io-client@1.5.4 node_modules/devkit/node_modules/engine.io-client
- socket.io-client@1.3.7 node_modules/devkit/node_modules/socket.io-client
- socket.io@1.3.7 node_modules/devkit/node_modules/socket.io
- devkit@3.1.1 node_modules/devkit
[root@develop devkit-core]# cd ..
[root@develop ~]# rm -rf devkit-core/
[root@develop ~]#
[root@develop ~]#
[root@develop ~]#
[root@develop ~]#
[root@develop ~]# git clone https://github.com/gameclosure/devkit-core.git
Cloning into 'devkit-core'...
remote: Counting objects: 2225, done.
remote: Total 2225 (delta 0), reused 0 (delta 0), pack-reused 2225
Receiving objects: 100% (2225/2225), 529.08 KiB | 622.00 KiB/s, done.
Resolving deltas: 100% (1278/1278), done.
Checking connectivity... done.
[root@develop ~]# cd devkit-core/
[root@develop devkit-core]# ls
modules  node_modules  package.json  scripts  src
[root@develop devkit-core]# nano -w package.json
[root@develop devkit-core]# npm install -g devkit
/usr/bin/devkit -> /usr/lib/node_modules/devkit/src/devkit.js

> bufferutil@1.2.1 install /usr/lib/node_modules/devkit/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/devkit/node_modules/bufferutil/.node-gyp"
make: Entering directory `/usr/lib/node_modules/devkit/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/usr/lib/node_modules/devkit/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/lib/node_modules/devkit/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/devkit/node_modules/utf-8-validate/.node-gyp"
make: Entering directory `/usr/lib/node_modules/devkit/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/lib/node_modules/devkit/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /usr/lib/node_modules/devkit/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/devkit/node_modules/bufferutil/.node-gyp"
make: Entering directory `/usr/lib/node_modules/devkit/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/usr/lib/node_modules/devkit/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/lib/node_modules/devkit/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/devkit/node_modules/utf-8-validate/.node-gyp"
make: Entering directory `/usr/lib/node_modules/devkit/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/lib/node_modules/devkit/node_modules/utf-8-validate/build'

> devkit@3.1.1 postinstall /usr/lib/node_modules/devkit
> sh scripts/postinstall.sh

/usr/lib
└─┬ devkit@3.1.1
  ├── bluebird@2.10.2
  ├─┬ body-parser@1.14.1
  │ ├── bytes@2.1.0
  │ ├── content-type@1.0.1
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── depd@1.1.0
  │ ├─┬ http-errors@1.3.1
  │ │ ├── inherits@2.0.1
  │ │ └── statuses@1.2.1
  │ ├── iconv-lite@0.4.12
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── qs@5.1.0
  │ ├─┬ raw-body@2.1.4
  │ │ └── unpipe@1.0.0
  │ └─┬ type-is@1.6.9
  │   ├── media-typer@0.3.0
  │   └── mime-types@2.1.7
  ├─┬ chalk@1.1.1
  │ ├── ansi-styles@2.1.0
  │ ├── escape-string-regexp@1.0.3
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.0
  │ └── supports-color@2.0.0
  ├─┬ compression@1.6.0
  │ ├─┬ accepts@1.3.0
  │ │ └── negotiator@0.6.0
  │ ├─┬ compressible@2.0.6
  │ │ └── mime-db@1.19.0
  │ ├── on-headers@1.0.1
  │ └── vary@1.1.0
  ├─┬ express@4.13.3
  │ ├─┬ accepts@1.2.13
  │ │ └── negotiator@0.5.3
  │ ├── array-flatten@1.1.1
  │ ├── content-disposition@0.5.0
  │ ├── cookie@0.1.3
  │ ├── cookie-signature@1.0.6
  │ ├── depd@1.0.1
  │ ├── escape-html@1.0.2
  │ ├── etag@1.7.0
  │ ├── finalhandler@0.4.0
  │ ├── fresh@0.3.0
  │ ├── merge-descriptors@1.0.0
  │ ├── methods@1.1.1
  │ ├── parseurl@1.3.0
  │ ├── path-to-regexp@0.1.7
  │ ├─┬ proxy-addr@1.0.8
  │ │ ├── forwarded@0.1.0
  │ │ └── ipaddr.js@1.0.1
  │ ├── qs@4.0.0
  │ ├── range-parser@1.0.2
  │ ├─┬ send@0.13.0
  │ │ ├── depd@1.0.1
  │ │ └── destroy@1.0.3
  │ ├── serve-static@1.10.0
  │ ├── utils-merge@1.0.0
  │ └── vary@1.0.1
  ├── ff@0.2.1
  ├── filesize@3.1.3
  ├─┬ fs-extra@0.24.0
  │ ├── graceful-fs@4.1.2
  │ ├── jsonfile@2.2.2
  │ ├── path-is-absolute@1.0.0
  │ └─┬ rimraf@2.4.3
  │   └─┬ glob@5.0.15
  │     ├─┬ inflight@1.0.4
  │     │ └── wrappy@1.0.1
  │     ├─┬ minimatch@3.0.0
  │     │ └─┬ brace-expansion@1.1.1
  │     │   ├── balanced-match@0.2.0
  │     │   └── concat-map@0.0.1
  │     └── once@1.3.2
  ├─┬ js-yaml@3.4.2
  │ ├─┬ argparse@1.0.2
  │ │ ├── lodash@3.10.1
  │ │ └── sprintf-js@1.0.3
  │ └── esprima@2.2.0
  ├── jsio@2.2.4
  ├── lockfile@1.0.1
  ├── mime@1.3.4
  ├── open@0.0.5
  ├─┬ optimist@0.6.1
  │ ├── minimist@0.0.10
  │ └── wordwrap@0.0.3
  ├── path-extra@1.0.3
  ├── printf@0.2.3
  ├── semver@4.3.6
  └─┬ socket.io@1.3.7
    ├─┬ debug@2.1.0
    │ └── ms@0.6.2
    ├─┬ engine.io@1.5.4
    │ ├── base64id@0.1.0
    │ ├─┬ debug@1.0.3
    │ │ └── ms@0.6.2
    │ ├─┬ engine.io-parser@1.2.2
    │ │ ├── after@0.8.1
    │ │ ├── arraybuffer.slice@0.0.6
    │ │ ├── base64-arraybuffer@0.1.2
    │ │ ├── blob@0.0.4
    │ │ └── utf8@2.1.0
    │ └─┬ ws@0.8.0
    │   ├─┬ bufferutil@1.2.1
    │   │ ├── bindings@1.2.1
    │   │ └── nan@2.0.9
    │   ├── options@0.0.6
    │   ├── ultron@1.0.2
    │   └── utf-8-validate@1.2.1
    ├─┬ has-binary-data@0.1.3
    │ └── isarray@0.0.1
    ├─┬ socket.io-adapter@0.3.1
    │ ├─┬ debug@1.0.2
    │ │ └── ms@0.6.2
    │ ├── object-keys@1.0.1
    │ └─┬ socket.io-parser@2.2.2
    │   └── debug@0.7.4
    ├─┬ socket.io-client@1.3.7
    │ ├── backo2@1.0.2
    │ ├── component-bind@1.0.0
    │ ├── component-emitter@1.1.2
    │ ├── debug@0.7.4
    │ ├─┬ engine.io-client@1.5.4
    │ │ ├── component-inherit@0.0.3
    │ │ ├─┬ debug@1.0.4
    │ │ │ └── ms@0.6.2
    │ │ ├─┬ has-cors@1.0.3
    │ │ │ └── global@2.0.1
    │ │ ├── parsejson@0.0.1
    │ │ ├── parseqs@0.0.2
    │ │ ├── parseuri@0.0.4
    │ │ └── xmlhttprequest@1.5.0
    │ ├── has-binary@0.1.6
    │ ├── indexof@0.0.1
    │ ├── object-component@0.0.3
    │ ├─┬ parseuri@0.0.2
    │ │ └─┬ better-assert@1.0.2
    │ │   └── callsite@1.0.0
    │ └── to-array@0.1.3
    └─┬ socket.io-parser@2.2.4
      ├── benchmark@1.0.0
      ├── debug@0.7.4
      └── json3@3.2.6

[root@develop devkit-core]#

NOW AS Normal User - dir devkit is just a directory for holding projects 

[bjones@develop devkit]$ devkit init bounce
            [apps]  Creating app using default template
                    Creating app using default application template
         [install]  Installing devkit-core...
                    Adding devkit-core
Cloning into '/home/bjones/.config/devkit/cache/3028584241264852653'...
remote: Counting objects: 2225, done.
remote: Total 2225 (delta 0), reused 0 (delta 0), pack-reused 2225
Receiving objects: 100% (2225/2225), 529.08 KiB | 580.00 KiB/s, done.
Resolving deltas: 100% (1278/1278), done.
Checking connectivity... done.
          [module]  running install scripts...

> devkit-core@3.0.2 preinstall /home/bjones/.config/devkit/cache/3028584241264852653
> sh scripts/preinstall.sh

Submodule 'modules/native-android' (https://github.com/gameclosure/native-android) registered for path 'modules/native-android'
Submodule 'modules/native-ios' (https://github.com/gameclosure/native-ios) registered for path 'modules/native-ios'
Submodule 'modules/squill' (https://github.com/gameclosure/squill) registered for path 'modules/squill'
Submodule 'modules/timestep' (https://github.com/gameclosure/timestep) registered for path 'modules/timestep'
Submodule 'node_modules/jsio' (https://github.com/gameclosure/js.io) registered for path 'node_modules/jsio'
Cloning into 'modules/native-android'...
remote: Counting objects: 4295, done.
remote: Total 4295 (delta 0), reused 0 (delta 0), pack-reused 4295
Receiving objects: 100% (4295/4295), 10.10 MiB | 332.00 KiB/s, done.
Resolving deltas: 100% (2500/2500), done.
Checking connectivity... done.
Submodule path 'modules/native-android': checked out 'df3ef01b9b82cada123ed97c0a879f14a5ba041d'
Cloning into 'modules/native-ios'...
remote: Counting objects: 4716, done.
remote: Total 4716 (delta 0), reused 0 (delta 0), pack-reused 4716
Receiving objects: 100% (4716/4716), 46.43 MiB | 536.00 KiB/s, done.
Resolving deltas: 100% (2873/2873), done.
Checking connectivity... done.
Submodule path 'modules/native-ios': checked out '221ee59562f6830b8098523920c3623893155254'
Cloning into 'modules/squill'...
remote: Counting objects: 1645, done.
remote: Total 1645 (delta 0), reused 0 (delta 0), pack-reused 1645
Receiving objects: 100% (1645/1645), 428.42 KiB | 602.00 KiB/s, done.
Resolving deltas: 100% (1024/1024), done.
Checking connectivity... done.
Submodule path 'modules/squill': checked out 'a5e4c5be4cd93074c0d6dbb60c0f509f96b8ec62'
Cloning into 'modules/timestep'...
remote: Counting objects: 6912, done.
remote: Total 6912 (delta 0), reused 0 (delta 0), pack-reused 6912
Receiving objects: 100% (6912/6912), 1.97 MiB | 562.00 KiB/s, done.
Resolving deltas: 100% (4463/4463), done.
Checking connectivity... done.
Submodule path 'modules/timestep': checked out 'aa7e53313aa1f01a28ddda56386939496c000b25'
fatal: destination path 'node_modules/jsio' already exists and is not an empty directory.
fatal: clone of 'https://github.com/gameclosure/js.io' into submodule path 'node_modules/jsio' failed

npm WARN ENOENT ENOENT, open '/home/bjones/.config/devkit/cache/3028584241264852653/node_modules/jsio/package.json'
npm WARN EPACKAGEJSON devkit-core@3.0.2 No license field.
npm ERR! Linux 2.6.32-504.16.2.el6.i686
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE
npm ERR! devkit-core@3.0.2 preinstall: `sh scripts/preinstall.sh`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the devkit-core@3.0.2 preinstall script 'sh scripts/preinstall.sh'.
npm ERR! This is most likely a problem with the devkit-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh scripts/preinstall.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls devkit-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bjones/.config/devkit/cache/3028584241264852653/npm-debug.log

          [devkit]  [error]  npm install for module 3028584241264852653 failed (exit code 1).

**Comment by jishnu7** [comment]
looks like this is fixed.
